from ubidots import temp_sensor

WIFI_SSID = 'CHANGEME' #SSID to Connect to
WIFI_PASSWORD = 'CHANGEME' # 

UBIDOTS_TOKEN = 'XXXX-XXXXXXXXXXXXX'
UBIDOTS_DEVICE_LABEL = 'unique-name'
SENSOR_PIN = 3 # ds18b20 One-Wire Pin
SLEEP_TIME = 60000 #Deep Sleep Time In ms.
temp_sensor(WIFI_SSID, WIFI_PASSWORD, UBIDOTS_TOKEN, UBIDOTS_DEVICE_LABEL, SENSOR_PIN, SLEEP_TIME)
